# Basic Jekyll configuration
title: Math Applets Collection
description: Interactive mathematics applets for educational purposes
baseurl: "/EducationApplets"

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/yourusername/EducationApplets

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
