name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .nojekyll file
        run: |
          touch ./docs/.nojekyll
          echo "Created .nojekyll file"
          ls -la ./docs/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean: true
          clean-exclude: |
            .nojekyll
